name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add more steps here
